Repository hygia-org/hygia, pull requests merged in 2023-01, with the labels that each got.

#38 ✨ Create a yaml parser random forest address model
  .github/CODEOWNERS
  src/main.py
  src/parser/YAML_parser.py
  src/parser/const.py
  src/parser/feature_engineering/__init__.py
  src/parser/feature_engineering_parser.py
  src/parser/initial/__init__.py
  src/parser/model_parser.py
  src/parser/parser_base.py
  src/yamls/basic_example.yaml
  tests/mock/fail/yaml_mock.yaml
  tests/mock/success/yaml_mock.yaml
  tests/parser/feature_engineering/__init__.py
  tests/parser/initial/__init__.py
  tests/parser/test_YAML_parser.py
  tests/parser/test_feature_engineering_parser.py
  tests/parser/test_model_parser.py
  tests/parser/test_parser_base.py
Labels: model

#41 #24 add class: feature_engineering/word_embedding
  .github/workflows/python-publish.yml
  requirements.txt
  src/data_pipeline/feature_engineering/word_embedding.py
  tests/data_pipeline/feature_engineering/test_word_embedding.py
Labels: feature-engineering

#27 #19 Yaml created for metabase initialization
  README.md
  makefile
  metabase/config/metabase_database_exemple.env
  metabase/config/mongo_exemple.env
  metabase/config/postgres_exemple.env
  metabase/metabase.yml
Labels: tech viability

#43 Create lib by poetry
  .github/workflows/CI.yml
  .gitignore
  pyproject.toml
  requirements-dev.txt
  src/hygia/lib.py
Labels: library

#40 Reestructure the repository
  .github/workflows/CI.yml
  config/default_config.yaml
  examples/MEXICO_1_simple_example.ipynb
  hygia/__init__.py
  hygia/data_pipeline/__init__.py
  hygia/data_pipeline/feature_engineering/__init__.py
  hygia/data_pipeline/feature_engineering/feature_engineering.py
  hygia/data_pipeline/feature_engineering/key_smash.py
  hygia/data_pipeline/feature_engineering/word_embedding.py
  hygia/data_pipeline/model/__init__.py
  hygia/data_pipeline/model/random_forest.py
  hygia/data_pipeline/pre_process_data/__init__.py
  hygia/data_pipeline/pre_process_data/pre_process_data.py
  hygia/main.py
  hygia/parser/YAML_parser.py
  hygia/parser/__init__.py
  hygia/parser/const.py
  hygia/parser/feature_engineering_parser.py
  hygia/parser/model_parser.py
  hygia/parser/parser_base.py
  hygia/parser/pre_processing_parser.py
  pyproject.toml
  src/.DS_Store
  src/data_pipeline/model/__init__.py
  src/data_pipeline/pre_process_data/__init__.py
  tests/data_pipeline/feature_engineering/test_feature_engineering.py
  tests/data_pipeline/feature_engineering/test_key_smash.py
  tests/data_pipeline/feature_engineering/test_word_embedding.py
  tests/mock/RandomForest_Ksmash_WordEmbedding.model
  tests/parser/test_YAML_parser.py
  tests/parser/test_feature_engineering_parser.py
  tests/parser/test_model_parser.py
  tests/parser/test_parser_base.py
Labels: enhancement

#53 Create CI to main push
  .github/workflows/ci-main.yml
  .github/workflows/ci.yml
Labels: tech viability

#50 28/adjust readme
  README.md
  assets/img/horizontal_logo.PNG
  metabase/README.md
Labels: documentation

#59 Update parser with new data pipeline
  config/default_config.yaml
  examples/MEXICO_retrain_predict_example.ipynb
  examples/yaml_example.ipynb
  hygia/data_pipeline/annotate_data/annotate_data.py
  hygia/data_pipeline/feature_engineering/feature_engineering.py
  hygia/data_pipeline/feature_engineering/regex.py
  hygia/data_pipeline/model/random_forest.py
  hygia/data_pipeline/pre_process_data/pre_process_data.py
  hygia/main.py
  hygia/parser/YAML_parser.py
  hygia/parser/annotate_data_parser.py
  hygia/parser/model_parser.py
  requirements-dev.txt
  tests/mock/success/yaml_mock.yaml
  tests/parser/test_annotate_parser.py
  tests/parser/test_model_parser.py
Labels: enhancement, yaml
